<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="AdminPDF.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <form  id="form2"  runat="server">
    <style>
  table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}
body{
    background-image:url(img/header-bg.jpg);
}
h3{
      color: white;
  }

</style>
    <center>
    <h3>Delete Lessons</h3>
    <br />
    
   

    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" AutoGenerateDeleteButton="True" Width="70%" DataKeyNames="ID" DataSourceID="SqlDataSource1">

            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="LastUpdated" HeaderText="LastUpdated" SortExpression="LastUpdated" />
            </Columns>
        </asp:GridView>
    <br />
        <br />
             <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:lessonGridview %>" DeleteCommand=" DELETE FROM [Recommendations] WHERE [ID]=@ID; DELETE FROM [Documents] WHERE [ID]=@ID;  DELETE FROM [Lessons] WHERE [ID]=@ID;  DELETE FROM [Ratings] WHERE [ID]=@ID;"  SelectCommand="SELECT [ID], [Name], [DocumentContent], [LastUpdated] FROM [Documents] ">
                 <DeleteParameters>
                     <asp:Parameter Name="ID" />
                 </DeleteParameters>
        </asp:SqlDataSource>
        <br />
        </form>
        </center>
</asp:Content>

