<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="DeleteResources.aspx.cs" Inherits="DeleteResources" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <!DOCTYPE html>
    <html>
    <head>
        <style type="text/css">
            table {
                border-collapse: collapse;
                border-spacing: 0;
                width: 60%;
                border: 1px solid #ddd;
            }

            h3 {
                color: white;
                text-align: center;
            }

            th, td {
                text-align: left;
                padding: 16px;
            }

            body {
                background-image: url(img/header-bg.jpg);
            }

            .btnRegister1 {
                float: none;
                border: none;
                border-radius: 1.5rem;
                padding: 1%;
                background: #fed136;
                color: black;
                font-weight: 50;
                width: 20%;
                cursor: pointer;
                border: 1px solid white;
            }
        </style>
    </head>
    <body>
        <form id="DeleteResourceForm" runat="server">
            <h3>Current Resource</h3>
            <br />

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" DataKeyNames="resourceID" DataSourceID="SqlDataSourceCurrentResources" AutoGenerateDeleteButton="True" HorizontalAlign="Center">
                <Columns runat="server">
                    <asp:BoundField DataField="resourceID" HeaderText="Resource ID" InsertVisible="False" ReadOnly="True" SortExpression="resourceID" />
                    <asp:BoundField DataField="title" HeaderText="Title" SortExpression="title" />
                    <asp:BoundField DataField="category" HeaderText="Category" SortExpression="category" />
                    <asp:BoundField DataField="Hyperlink" HeaderText="Hyperlink" SortExpression="Hyperlink" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="SqlDataSourceCurrentResources" runat="server" ConnectionString="<%$ ConnectionStrings:manageUsers %>" DeleteCommand="DELETE FROM [Resources] WHERE [resourceID]=@resourceID;" SelectCommand="SELECT [resourceID], [title], [category], [Hyperlink] FROM [Resources]">
                <DeleteParameters>
                    <asp:Parameter Name="resourceID" />
                </DeleteParameters>
            </asp:SqlDataSource>

        </form>





    </body>

    </html>

</asp:Content>

