<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <title>Hip Hop IllumiNation.com</title>
    <form  id="form2"  runat="server">
    <style>
  table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 60%;
  border: 1px solid #ddd;
}
  h3{
      color: white;
  }

th, td {
  text-align: left;
  padding: 16px;
}
    .search-box{
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        background-color: gray;
        height: 40px;
        border-radius:40px;
        padding: 10px;
    }
    .search-box:hover > .search-txt{
        width: 240px;
        padding: 0 6px;
    }
        .search-box:hover > .search-btn{
        background: white;
    }
    .search-btn{
        color:gold;
        float: right;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background-color: white;
        display: flex;
        justify-content: center;
        align-items: center;
        transition: 0.4s;
    }
    .search-txt {
        border: none;
        background: none;
        outline: none;
        float: left;
        padding: 0;
        color: white;
        font-size: 16px;
        transition: 0.4s;
        line-height: 40px;
        width: 0px;
    }

        body{
    background-image:url(img/header-bg.jpg);
}
        .btnRegister1
   {
    float: none;
    
    border: none;
    border-radius: 1.5rem;
    padding: 1%;
    background: #fed136;
    color: black;
    font-weight: 50;
    width: 20%;
    cursor: pointer;
    border:1px solid white;
}
            .btn-secondary
{
    
background-color:#fed136;
}
    
</style>
    <center>
    <h3>
        <asp:Button class="btnRegister1" ID="Button1" runat="server" Text="Youth Users" OnClick="Button1_Click" />
        <asp:Button class="btnRegister1" ID="Button2" runat="server" Text="Adult Users" OnClick="Button2_Click" />
        </h3>
        
    <br />
       <asp:Panel ID="panel" runat="server" DefaultButton="btnSearch">
        <asp:TextBox ID="txtSearch" runat="server" class="form-control-sm" Width="300px" OnTextChanged="txtSearch_TextChanged"></asp:TextBox>
              &nbsp;
    <asp:Button ID="btnSearch" runat="server" class="btn btn-secondary" Text="Search" OnClick="btnSearch_Click" />
        </asp:Panel>
    <asp:GridView ID="GridView1" Visible="false" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" DataKeyNames="accountID" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" HorizontalAlign="Center" >
    <Columns runat="server">
        <asp:BoundField DataField="accountID" HeaderText=" User Account ID" InsertVisible="False" ReadOnly="True" SortExpression="accountID" />
        <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" />        
        <asp:BoundField DataField="email" HeaderText="Email Address" SortExpression="email" />
        <asp:BoundField DataField="lastUpdated" HeaderText="Date Created" SortExpression="lastUpdated" />
    </Columns>
</asp:GridView>       
        
    
    
    <asp:GridView ID="GridView2" Visible="false" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" DataKeyNames="accountID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" HorizontalAlign="Center">
    <Columns runat="server">
        <asp:BoundField DataField="accountID" HeaderText="User Account ID" InsertVisible="False" ReadOnly="True" SortExpression="accountID" />
        <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" />        
        <asp:BoundField DataField="email" HeaderText="Email Address" SortExpression="email" />
        <asp:BoundField DataField="lastUpdated" HeaderText="Date Created" SortExpression="lastUpdated" />
    </Columns>
</asp:GridView>         
            
        </form>
        </center>

<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:manageUsers %>"  DeleteCommand= "DELETE FROM [Adult] WHERE [accountID]=@accountID;DELETE FROM [Lessons] WHERE [accountID]=@accountID;DELETE FROM [Feedback] WHERE [accountID]=@accountID; DELETE FROM [Ratings] WHERE [ID]=@accountID;DELETE FROM [Recommendations] WHERE [accountID]=@accountID;DELETE FROM [LoginInfo] WHERE [accountID]=@accountID" SelectCommand="SELECT accountID, username, email, lastUpdated FROM LoginInfo WHERE accountType = 'Adult'">
    <DeleteParameters>            
        <asp:Parameter Name="accountID" Type="Int32"/>
    </DeleteParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:manageUsers %>"  DeleteCommand= "DELETE FROM [Youth] WHERE [accountID]=@accountID;DELETE FROM [Lessons] WHERE [accountID]=@accountID;DELETE FROM [Feedback] WHERE [accountID]=@accountID; DELETE FROM [Ratings] WHERE [ID]=@accountID;DELETE FROM [Recommendations] WHERE [accountID]=@accountID;DELETE FROM [LoginInfo] WHERE [accountID]=@accountID" SelectCommand="SELECT accountID, username, email, lastUpdated FROM LoginInfo WHERE accountType = 'Youth'">
    <DeleteParameters>            
        <asp:Parameter Name="accountID" Type="Int32"/>
    </DeleteParameters>
    </asp:SqlDataSource>
      
</asp:Content>


