
﻿<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <title>Hip Hop IllumiNation.com</title>
    <form  id="form2"  runat="server">
    <style>
  table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 60%;
  border: 1px solid #ddd;
}
  h3{
      color: white;
  }

th, td {
  text-align: left;
  padding: 16px;
}

        body{
    background-image:url(img/header-bg.jpg);
}
        .btnRegister1
   {
    float: none;
    
    border: none;
    border-radius: 1.5rem;
    padding: 1%;
    background: #fed136;
    color: black;
    font-weight: 50;
    width: 20%;
    cursor: pointer;
    border:1px solid white;
}
    
</style>
    <center>
    <h3>
        <asp:Button class="btnRegister1" ID="Button1" runat="server" Text="Youth Users" OnClick="Button1_Click" />
        <asp:Button class="btnRegister1" ID="Button2" runat="server" Text="Adult Users" OnClick="Button2_Click" />
        </h3>
        
    <br />
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" DataKeyNames="accountID" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" HorizontalAlign="Center" >
    <Columns runat="server">
        <asp:BoundField DataField="accountID" HeaderText=" User Account ID" InsertVisible="False" ReadOnly="True" SortExpression="accountID" />
        <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" />        
        <asp:BoundField DataField="email" HeaderText="Email Address" SortExpression="email" />
        <asp:BoundField DataField="lastUpdated" HeaderText="Date Created" SortExpression="lastUpdated" />
    </Columns>
</asp:GridView>       
        
    
    
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" CssClass="table-dark table-hover" DataKeyNames="accountID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" HorizontalAlign="Center">
    <Columns runat="server">
        <asp:BoundField DataField="accountID" HeaderText="User Account ID" InsertVisible="False" ReadOnly="True" SortExpression="accountID" />
        <asp:BoundField DataField="username" HeaderText="Username" SortExpression="username" />        
        <asp:BoundField DataField="email" HeaderText="Email Address" SortExpression="email" />
        <asp:BoundField DataField="lastUpdated" HeaderText="Date Created" SortExpression="lastUpdated" />
    </Columns>
</asp:GridView>         
        


            
        </form>
        </center>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:manageUsers %>"  DeleteCommand= "DELETE FROM [Adult] WHERE [accountID]=@accountID;DELETE FROM [Lessons] WHERE [accountID]=@accountID;DELETE FROM [Feedback] WHERE [accountID]=@accountID; DELETE FROM [Ratings] WHERE [ID]=@accountID;DELETE FROM [Recommendations] WHERE [accountID]=@accountID;DELETE FROM [LoginInfo] WHERE [accountID]=@accountID" SelectCommand="SELECT accountID, username, email, lastUpdated FROM LoginInfo WHERE accountType = 'Adult'">
    <DeleteParameters>            
        <asp:Parameter Name="accountID" Type="Int32"/>
    </DeleteParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:manageUsers %>"  DeleteCommand= "DELETE FROM [Youth] WHERE [accountID]=@accountID;DELETE FROM [Lessons] WHERE [accountID]=@accountID;DELETE FROM [Feedback] WHERE [accountID]=@accountID; DELETE FROM [Ratings] WHERE [ID]=@accountID;DELETE FROM [Recommendations] WHERE [accountID]=@accountID;DELETE FROM [LoginInfo] WHERE [accountID]=@accountID" SelectCommand="SELECT accountID, username, email, lastUpdated FROM LoginInfo WHERE accountType = 'Youth'">
    <DeleteParameters>            
        <asp:Parameter Name="accountID" Type="Int32"/>
    </DeleteParameters>
    </asp:SqlDataSource>
      
</asp:Content>


